import React from "react";
import Head from "next/head";
import Friend from "@/components/screens/friend/Friend";

export default function FriendPage() {
  return (
    <>
      <Head>
        <title>Friend 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Friend />
    </>
  );
}
