import React from "react";
import Header from "@/components/header/Header";
import Head from "next/head";
import About from "@/components/screens/about/About";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
    </>
  );
}
