import React from "react";
import Head from "next/head";
import Contacts from "@/components/screens/contacts/Contacts";

export default function ContactsPage() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contacts />
    </>
  );
}
