import React from "react";
import Head from "next/head";
import Friends from "@/components/screens/friends/Friends";

export default function FriendsPage() {
  return (
    <>
      <Head>
        <title>Friends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Friends />
    </>
  );
}
